#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_http_server.h"
#include "esp_log.h"
#include "cJSON.h"
#include "servos.h"
#include "state.h"
#include "web_server.h"
#include "web_assets.h" // generated by embed-web.py

static const char *TAG = "web";
static httpd_handle_t g_server = NULL;

static void shuffle_array(uint8_t *arr, size_t n)
{
    for (size_t i = n - 1; i > 0; i--) {
        size_t j = rand() % (i + 1);
        uint8_t t = arr[j];
        arr[j] = arr[i];
        arr[i] = t;
    }
}

static void drop_sequence_task(void *arg)
{
    uint8_t order[6] = {0, 1, 2, 3, 4, 5};
    shuffle_array(order, 6);
    state_save_sequence(order, 0);

    uint32_t interval = state_get_drop_interval_ms(g_state.difficulty);
    uint8_t i = 0;

    while (i < 6) {
        if (g_state.double_drop && i < 5) {
            uint8_t pair[2] = { order[i], order[i + 1] };
            servos_drop_batch(pair, 2);
            i += 2;
        } else {
            servos_drop(order[i]);
            i++;
        }
        state_save_sequence(order, i);
        state_increment_drop_count();

        if (i < 6) {
            if (g_state.difficulty == DIFFICULTY_RANDOM) {
                interval = state_get_drop_interval_ms(DIFFICULTY_RANDOM);
            }
            vTaskDelay(pdMS_TO_TICKS(interval));
        }
    }

    vTaskDelete(NULL);
}

static esp_err_t api_status_handler(httpd_req_t *req)
{
    cJSON *root = cJSON_CreateObject();
    cJSON_AddNumberToObject(root, "difficulty", g_state.difficulty);
    cJSON_AddBoolToObject(root, "double_drop", g_state.double_drop);
    cJSON_AddNumberToObject(root, "drop_count", g_state.drop_count);

    cJSON *held = cJSON_CreateArray();
    for (int i = 0; i < 6; i++) cJSON_AddItemToArray(held, cJSON_CreateBool(servos_is_held(i)));
    cJSON_AddItemToObject(root, "held", held);

    const char *json = cJSON_Print(root);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, json);
    free((void *)json);
    cJSON_Delete(root);
    return ESP_OK;
}

static esp_err_t api_drop_handler(httpd_req_t *req)
{
    char buf[16];
    int len = httpd_req_recv(req, buf, sizeof(buf) - 1);
    if (len <= 0) {
        // Drop all (start sequence)
        xTaskCreate(drop_sequence_task, "drop_seq", 4096, NULL, 4, NULL);
        httpd_resp_set_type(req, "application/json");
        httpd_resp_sendstr(req, "{\"status\":\"started\"}");
        return ESP_OK;
    }
    buf[len] = 0;

    cJSON *json = cJSON_Parse(buf);
    if (!json) return ESP_FAIL;

    cJSON *id_item = cJSON_GetObjectItem(json, "id");
    if (cJSON_IsNumber(id_item)) {
        uint8_t id = (uint8_t)id_item->valuedouble;
        if (id >= 1 && id <= 6) {
            servos_drop(id - 1);
        }
    }

    cJSON_Delete(json);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, "{\"status\":\"ok\"}");
    return ESP_OK;
}

static esp_err_t api_config_handler(httpd_req_t *req)
{
    char buf[256];
    int len = httpd_req_recv(req, buf, sizeof(buf) - 1);
    if (len <= 0) return ESP_FAIL;
    buf[len] = 0;

    cJSON *json = cJSON_Parse(buf);
    if (!json) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "bad json");
        return ESP_FAIL;
    }

    cJSON *diff = cJSON_GetObjectItem(json, "difficulty");
    if (cJSON_IsNumber(diff)) state_set_difficulty((difficulty_t)diff->valuedouble);

    cJSON *dd = cJSON_GetObjectItem(json, "double_drop");
    if (cJSON_IsBool(dd)) state_set_double_drop(cJSON_IsTrue(dd));

    cJSON_Delete(json);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, "{\"status\":\"ok\"}");
    return ESP_OK;
}

static esp_err_t root_get_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html; charset=utf-8");
    httpd_resp_sendstr(req,
        "<!DOCTYPE html>"
        "<html><head>"
        "<meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=5,user-scalable=yes\">"
        "<title>NukCPGDrop</title>"
        "<link rel=\"icon\" href=\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'><text y='14' font-size='14'>🧲</text></svg>\">"
        "<base href=\"/\">"
        "<link href=\"/css/app.css\" rel=\"stylesheet\">"
        "<link href=\"/NukCPGDrop.Ui.styles.css\" rel=\"stylesheet\">"
        "</head><body>"
        "<div id=\"app\">Loading...</div>"
        "<div id=\"blazor-error-ui\">Connection error</div>"
        "<script src=\"/_framework/blazor.webassembly.js\"></script>"
        "</body></html>"
    );
    return ESP_OK;
}

static const httpd_uri_t uris[] = {
    { .uri = "/api/status", .method = HTTP_GET,  .handler = api_status_handler },
    { .uri = "/api/drop",   .method = HTTP_POST, .handler = api_drop_handler },
    { .uri = "/api/config", .method = HTTP_POST, .handler = api_config_handler },
    { .uri = "/",           .method = HTTP_GET,  .handler = root_get_handler },
};

esp_err_t web_server_start(void)
{
    httpd_config_t cfg = HTTPD_DEFAULT_CONFIG();
    cfg.max_uri_handlers = 16;
    cfg.stack_size = 8192;
    cfg.lru_purge_enable = true;

    ESP_RETURN_ON_ERROR(httpd_start(&g_server, &cfg), TAG, "httpd start");

    for (size_t i = 0; i < sizeof(uris) / sizeof(uris[0]); i++) {
        httpd_register_uri_handler(g_server, &uris[i]);
    }

    ESP_LOGI(TAG, "HTTP server running on :80");
    return ESP_OK;
}

esp_err_t web_server_stop(void)
{
    if (g_server) {
        httpd_stop(g_server);
        g_server = NULL;
    }
    return ESP_OK;
}
